### ISSUE TITLE
Can css be used to theme the main terminal window?

### ISSUE THREAD

**Issue by sagotsky** [cedlemo/Tortosa#2]
If not, could this be a feature request?

**Comment by cedlemo** [comment]
Sorry I am late to answer you. I guess you are talking about the main window of tortosa and its background color. No css cannot be used (for now). Could it be a feature request? maybe,  I think that it can be improved. (In fatc, in the first releases, tortosa was able to read the css and get the color you have set for GtkWindow so you had'nt have to set the color in the tortosarc).

So just you can use GtkWindow in the css in order to configure properties except the background color.
